version: 2.1

orbs:
  docker: circleci/docker@1.2.1

commands:
  docker-build-and-publish:
    description: Build and publish a single image

    parameters:
      tag:
        type: string

    steps:
      - docker/check
      - run:
          name: Generate version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
                "$CIRCLE_SHA1" \
                "$CIRCLE_TAG" \
                "$CIRCLE_PROJECT_USERNAME" \
                "$CIRCLE_PROJECT_REPONAME" \
                "$CIRCLE_BUILD_URL" > version.json
      - docker/build:
          image: ${DOCKER_IMAGE}
          tag: <<parameters.tag>>
          dockerfile: containers/Dockerfile
          step-name: build crlite container
      - docker/push:
          image: ${DOCKER_IMAGE}
          tag: <<parameters.tag>>
          step-name: push crlite container

jobs:
  golang-build-and-test:
    docker:
      # specify the version
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/mozilla.com/OneCRL-Tools/
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Download and build
          command: go get -v -t -d ./...
      - run:
          name: gofmt
          command: >
            if [ -n "$(gofmt -l .)" ]; then
              echo "Go code is not formatted:"; gofmt -d .; exit 1;
            fi
      - run:
          name: Test
          command: go test -v -short ./...

      - run:
          name: Test with race-finder
          command: go test -race -short ./...

  publish-dev-pods:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker-build-and-publish:
          tag: ${CIRCLE_SHA1}

  publish-tagged-pods:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker-build-and-publish:
          tag: ${CIRCLE_TAG}

  publish-latest-pods:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker-build-and-publish:
          tag: latest

workflows:
  version: 2

  untagged-build:
    jobs:
      - golang-build-and-test
      - publish-dev-pods:
          filters:
            branches:
              only: dev
          requires:
            - golang-build-and-test
      - publish-latest-pods:
          filters:
            branches:
              only: main
          requires:
            - golang-build-and-test

  tagged-build:
    jobs:
      - golang-build-and-test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish-tagged-pods:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - golang-build-and-test
